title: Data Warehouse
author: ashwinagalcha
email: ashwinagalcha94.iitkgp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ETL Data Pipelines for Data Warehouse

# social links
twitter_username: aagalcha
github_username:  ashwinagalcha

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
